// Created by iWeb 3.0.4 local-build-20120403

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-5,5,10,200),url:'4_Initiating_the_first_events_files/stroke.png'},{rect:new IWRect(-5,-5,10,10),url:'4_Initiating_the_first_events_files/stroke_1.png'},{rect:new IWRect(5,-5,385,10),url:'4_Initiating_the_first_events_files/stroke_2.png'},{rect:new IWRect(390,-5,10,10),url:'4_Initiating_the_first_events_files/stroke_3.png'},{rect:new IWRect(390,5,10,200),url:'4_Initiating_the_first_events_files/stroke_4.png'},{rect:new IWRect(390,205,10,10),url:'4_Initiating_the_first_events_files/stroke_5.png'},{rect:new IWRect(5,205,385,10),url:'4_Initiating_the_first_events_files/stroke_6.png'},{rect:new IWRect(-5,205,10,10),url:'4_Initiating_the_first_events_files/stroke_7.png'}],new IWSize(395,210)),stroke_1:new IWStrokeParts([{rect:new IWRect(-5,5,10,390),url:'4_Initiating_the_first_events_files/stroke_8.png'},{rect:new IWRect(-5,-5,10,10),url:'4_Initiating_the_first_events_files/stroke_9.png'},{rect:new IWRect(5,-5,390,10),url:'4_Initiating_the_first_events_files/stroke_10.png'},{rect:new IWRect(395,-5,10,10),url:'4_Initiating_the_first_events_files/stroke_11.png'},{rect:new IWRect(395,5,10,390),url:'4_Initiating_the_first_events_files/stroke_12.png'},{rect:new IWRect(395,395,10,10),url:'4_Initiating_the_first_events_files/stroke_13.png'},{rect:new IWRect(5,395,390,10),url:'4_Initiating_the_first_events_files/stroke_14.png'},{rect:new IWRect(-5,395,10,10),url:'4_Initiating_the_first_events_files/stroke_15.png'}],new IWSize(400,400))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('4_Initiating_the_first_events_files/4_Initiating_the_first_eventsMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');Widget.onload();fixAllIEPNGs('../../../../Media/transparent.gif');fixupAllIEPNGBGs();BlogFixupPreviousNext();applyEffects()}
function onPageUnload()
{Widget.onunload();}
