// Created by iWeb 3.0.4 local-build-20130905

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-5,5,10,367),url:'5_On_Culturing_Iron_Limited_Phytoplankton_files/stroke.png'},{rect:new IWRect(-5,-5,10,10),url:'5_On_Culturing_Iron_Limited_Phytoplankton_files/stroke_1.png'},{rect:new IWRect(5,-5,398,10),url:'5_On_Culturing_Iron_Limited_Phytoplankton_files/stroke_2.png'},{rect:new IWRect(403,-5,10,10),url:'5_On_Culturing_Iron_Limited_Phytoplankton_files/stroke_3.png'},{rect:new IWRect(403,5,10,367),url:'5_On_Culturing_Iron_Limited_Phytoplankton_files/stroke_4.png'},{rect:new IWRect(403,372,10,11),url:'5_On_Culturing_Iron_Limited_Phytoplankton_files/stroke_5.png'},{rect:new IWRect(5,372,398,11),url:'5_On_Culturing_Iron_Limited_Phytoplankton_files/stroke_6.png'},{rect:new IWRect(-5,372,10,11),url:'5_On_Culturing_Iron_Limited_Phytoplankton_files/stroke_7.png'}],new IWSize(408,377)),stroke_1:new IWStrokeParts([{rect:new IWRect(-5,5,10,289),url:'5_On_Culturing_Iron_Limited_Phytoplankton_files/stroke_8.png'},{rect:new IWRect(-5,-5,10,10),url:'5_On_Culturing_Iron_Limited_Phytoplankton_files/stroke_9.png'},{rect:new IWRect(5,-5,214,10),url:'5_On_Culturing_Iron_Limited_Phytoplankton_files/stroke_10.png'},{rect:new IWRect(219,-5,10,10),url:'5_On_Culturing_Iron_Limited_Phytoplankton_files/stroke_11.png'},{rect:new IWRect(219,5,10,289),url:'5_On_Culturing_Iron_Limited_Phytoplankton_files/stroke_12.png'},{rect:new IWRect(219,294,10,11),url:'5_On_Culturing_Iron_Limited_Phytoplankton_files/stroke_13.png'},{rect:new IWRect(5,294,214,11),url:'5_On_Culturing_Iron_Limited_Phytoplankton_files/stroke_14.png'},{rect:new IWRect(-5,294,10,11),url:'5_On_Culturing_Iron_Limited_Phytoplankton_files/stroke_15.png'}],new IWSize(224,300))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('5_On_Culturing_Iron_Limited_Phytoplankton_files/5_On_Culturing_Iron_Limited_PhytoplanktonMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('../../../../Media/transparent.gif');BlogFixupPreviousNext();applyEffects()}
function onPageUnload()
{Widget.onunload();}
