// Created by iWeb 3.0.4 local-build-20120403

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,81),url:'12_This_Week_In_A_Nutshell_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'12_This_Week_In_A_Nutshell_files/stroke_9.png'},{rect:new IWRect(1,-1,188,2),url:'12_This_Week_In_A_Nutshell_files/stroke_10.png'},{rect:new IWRect(189,-1,2,2),url:'12_This_Week_In_A_Nutshell_files/stroke_11.png'},{rect:new IWRect(189,1,2,81),url:'12_This_Week_In_A_Nutshell_files/stroke_12.png'},{rect:new IWRect(189,82,2,2),url:'12_This_Week_In_A_Nutshell_files/stroke_13.png'},{rect:new IWRect(1,82,188,2),url:'12_This_Week_In_A_Nutshell_files/stroke_14.png'},{rect:new IWRect(-1,82,2,2),url:'12_This_Week_In_A_Nutshell_files/stroke_15.png'}],new IWSize(190,83)),stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,77),url:'12_This_Week_In_A_Nutshell_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'12_This_Week_In_A_Nutshell_files/stroke_1.png'},{rect:new IWRect(1,-1,661,2),url:'12_This_Week_In_A_Nutshell_files/stroke_2.png'},{rect:new IWRect(662,-1,2,2),url:'12_This_Week_In_A_Nutshell_files/stroke_3.png'},{rect:new IWRect(662,1,2,77),url:'12_This_Week_In_A_Nutshell_files/stroke_4.png'},{rect:new IWRect(662,78,2,2),url:'12_This_Week_In_A_Nutshell_files/stroke_5.png'},{rect:new IWRect(1,78,661,2),url:'12_This_Week_In_A_Nutshell_files/stroke_6.png'},{rect:new IWRect(-1,78,2,2),url:'12_This_Week_In_A_Nutshell_files/stroke_7.png'}],new IWSize(663,79))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('12_This_Week_In_A_Nutshell_files/12_This_Week_In_A_NutshellMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');Widget.onload();BlogFixupPreviousNext();applyEffects()}
function onPageUnload()
{Widget.onunload();}
